Update AVAW_CVAT_BBOX.py
  File "c:\users\gkoinig\desktop\avaw_cv-waste\avaw_bbox\avaw_cvat_bbox.py", line 80, in flip_ud
    self.clear_undo_archive()
TypeError: DataAugmentor.clear_undo_archive() missing 1 required positional argument: 'owner'

Fixed errenous function definition for DataAugmentor.clear_undo_archive(self,owner)

Removed: OWNER

Result
DataAugmentor.clear_undo_archive(self)

Reason:
Owner is defined class wide in DataAugmentor